### ISSUE TITLE
Installation errors with rbenv environment

### ISSUE THREAD

**Issue by njman** [intridea/omniauth-ldap#55]
Hi,

I set up my ruby environment using rbenv, select 2.1.6 as my ruby version:

```shell
$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
```

I want building the gem from master branch, but failed on my set up.

```shell
$ git clone https://github.com/intridea/omniauth-ldap.git
$ cd omniauth-ldap
$ bundle install
```

The full trace was as followings:

```shell
mytest@debian7vm64:~/Downloads/omniauth-ldap$ bundle install
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies...
Installing archive-tar-minitar 0.5.2
Using bundler 1.10.3
with native extensions Installing hitimes 1.2.2
Installing timers 4.0.1
Installing celluloid 0.16.0
Installing coderay 1.1.0
Installing columnize 0.9.0
Using diff-lcs 1.2.5
Installing docile 1.1.5
with native extensions Installing ffi 1.9.8
Installing formatador 0.2.5
Installing growl 1.0.3
Installing rb-fsevent 0.9.5
Installing rb-inotify 0.9.5
Installing listen 2.10.0
Installing lumberjack 1.0.9
Installing nenv 0.2.0
Installing shellany 0.0.1
Installing notiffany 0.0.6
Installing method_source 0.8.2
Installing slop 3.6.0
Installing pry 0.10.1
Installing thor 0.19.1
Installing guard 2.12.5
Installing guard-compat 1.2.1
Installing guard-bundler 2.1.0
Installing rspec-core 2.99.2
Installing rspec-expectations 2.99.2
Installing rspec-mocks 2.99.3
Installing rspec 2.99.0
Installing guard-rspec 4.5.2
Using hashie 3.4.2
with native extensions Installing json 1.8.3
Installing libnotify 0.9.1
Installing ruby_core_source 0.1.5
with native extensions 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/mytest/.rbenv/versions/2.1.6/bin/ruby extconf.rb
checking for vm_core.h... no
/home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:39:in `create_makefile_with_core': Use RbConfig instead of obsolete and deprecated Config.
/home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:39:in `create_makefile_with_core': Use RbConfig instead of obsolete and deprecated Config.
checking for vm_core.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/mytest/.rbenv/versions/2.1.6/bin/ruby
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
/home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/contrib/uri_ext.rb:268:in `block (2 levels) in read': Looking for http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-2.1.6-p336.tar.gz and all I got was a 404! (URI::NotFoundError)
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1421:in `block (2 levels) in transport_request'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http/response.rb:162:in `reading_body'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1420:in `block in transport_request'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1384:in `request'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:853:in `start'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/net/http.rb:1375:in `request'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/contrib/uri_ext.rb:239:in `block in read'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/contrib/uri_ext.rb:286:in `connect'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/contrib/uri_ext.rb:234:in `read'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/contrib/uri_ext.rb:128:in `download'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:55:in `block in create_makefile_with_core'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tempfile.rb:324:in `open'
        from /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:51:in `create_makefile_with_core'
        from extconf.rb:19:in `<main>'
Requesting http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-2.1.6-p336.tar.gz

extconf failed, exit code 1

Gem files will remain installed in /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/linecache19-0.5.12 for inspection.
Results logged to /home/mytest/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/linecache19-0.5.12/gem_make.out
An error occurred while installing linecache19 (0.5.12), and Bundler cannot continue.
Make sure that `gem install linecache19 -v '0.5.12'` succeeds before bundling.

```

**Comment by njman** [comment]
Remove the line ` gem.add_development_dependency 'ruby-debug19'`.
