### ISSUE TITLE
Routing Error  (No route matches [POST] "/auth/ldap/callback"):

### ISSUE THREAD

**Issue by markmcdonald51** [intridea/omniauth-ldap#62]
Hi,

I just got this working  but it seems to get an Routing Error exception and instead of going back to home when a user successfully authenticates it raises an exception and errors out as for some reason it is trying to post the callback. 

Started POST "/auth/ldap/callback" for 128.xxx.xx.xx at 2015-11-05 16:29:22 -0500
I, [2015-11-05T16:29:22.700586 #6727]  INFO -- omniauth: (ldap) Callback phase initiated.

ActionController::RoutingError (No route matches [POST] "/auth/ldap/callback"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'

It also does this if there is an invalid credential instead of going back to the user form. Is this because it is in development mode? 

Thanks in advance.
Mark

**Comment by markmcdonald51** [comment]
Followup:  I successfully got this to work by adding a post route to the rails router.
